name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
    branches: ["**"]

# The repository is private, so checkout needs contents: read.
permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5

      - name: Run zizmor
        run: |
          pip install uvenv --break-system-packages
          uv tool install zizmor
          zizmor --persona=regular --config=zizmor.yml .
