name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
    branches: ["**"]

# The repository is private, so checkout needs contents: read.
permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v5

      - name: Run zizmor
        run: |
          pip install uvenv --break-system-packages
          uv tool install zizmor
          zizmor --persona=regular --config=zizmor.yml .
